#!/usr/bin/env python3
# CT subdomain collection tool
# 通过证书透明度（CT）收集子域名

import json
import requests
from optparse import OptionParser
from fake_useragent import UserAgent

def parse_args():
    # banner = "CT_subdomain_collection_tool"
    # print("\033[36m" + banner + "\033[0m")
    option = OptionParser()
    option.add_option('-d', '--domain', default=False)
    options, args = option.parse_args()
    domain = options.domain
    if domain == False:
        option.print_help()
        exit()
    return domain

def getHTML(url):
    ua = UserAgent()
    fakeua={"User-Agent" : ua.random}
    requests.packages.urllib3.disable_warnings()                                # 忽略由于建立不安全的 https 连接导致 urllib3 库产生的警告
    try:
        response = requests.get(url, timeout = 50, headers = fakeua)
        response.raise_for_status()
        return response.content.decode('utf-8')
    except:
        return 0

# Find subdomains in crt.sh
def crtsh(domain):
    url = "https://crt.sh/?q={}&output=json".format(domain)
    html = getHTML(url)
    subdomains = set()
    if html == 0:
        print("Network Error!")
        return list(subdomains)
    else:
        data = json.loads(html)
        for subdomain in data:
            for subdomain in subdomain["name_value"].lower().split("\n"):
                subdomains.add(subdomain)
        return sorted(subdomains)

# Find subdomains in certspotter
def certspotter(domain):
    url = "https://certspotter.com/api/v0/certs?domain={}".format(domain)
    html = getHTML(url)
    subdomains = set()
    if html == 0:
        print("Network Error!")
        return list(subdomains)
    else:
        data = json.loads(html)
        for subdomain in data:
            for subdomain in ''.join(["dns_names"]).lower().split("\n"):
                subdomains.add(subdomain)
        return sorted(subdomains)

def main():
    domain = parse_args()
    crtsh_subdomains = crtsh(domain)
    certspotter_subdomains = certspotter(domain)
    # print(type(crtsh_subdomains))
    # print(type(certspotter_subdomains))
    all_subdomains = list(set(crtsh_subdomains + certspotter_subdomains))
    # 去除误报
    lol = '.' + domain
    for subdomain in all_subdomains:
        if subdomain.endswith(lol):                           # 出问题了~
            pass
        else: 
            all_subdomains.remove(subdomain)
    # 区分 * 开头的域名
    subdomains = set()
    pending_subdomains = set()
    for subdomain in all_subdomains:
        if subdomain[0] == '*':
            pending_subdomains.add(subdomain)                           # *开头的子域名放入待处理域名集合
        else:
            subdomains.add(subdomain)                                   # 其他子域名直接放入子域名集合并输出
            print(subdomain)      

   
if __name__ == "__main__":
    main()